// <auto-generated />
namespace FlorariaPOCData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test_oana_serviciu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_oana_serviciu));
        
        string IMigrationMetadata.Id
        {
            get { return "201605201113176_test_oana_serviciu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
